### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mfbx9da4** [mfbx9da4/identify_my_ipad#1]
- [ ] Add more info to product page 
  - Hardware model, other model names, Images in different colors
- [ ] Vet the products better and add more products
- [ ] Improve structured data for rich results
- [ ] pay for google ads
- [ ] Launch on product hunt
- [ ] Linkbacks ...
